name: Generate Readme
on: 
  push:
    branches:    
      - master
jobs:
  generate-readme:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift ./.github/main.swift
      - run: chmod +x ./.github/deploy.sh
      - run: ./.github/deploy.sh
